language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.2.8
  - 2.3.1
  - 2.3.5
  - 2.4.2
  - 2.5.1

env:
  global:
    - STREAM_REGION=qa

matrix:
  fast_finish: true
#  allow_failures:
#    - rvm: '2.4.2'
